### ISSUE TITLE
Add flag for indexing

### ISSUE THREAD

**Issue by alexabbott** [yu-iskw/bigquery-to-datastore#10]
What is the reason for setting setExcludedFromIndexes to true? Ideally this would be an additional flag when running the main shell script

**Comment by yu-iskw** [comment]
There are two reason why `setExcludedFromINdexes` is `true` as default. First, putting data types related dates cost very much. Second, having indices for all colums make data size very large.

As you might saw, there is a plan to specify indexed columns.
https://github.com/yu-iskw/bigquery-to-datastore/issues/6
