### ISSUE TITLE
Upgrade apache beam to 2.16.0

### ISSUE THREAD

**Issue by yu-iskw** [yu-iskw/bigquery-to-datastore#13]
Apache Beam 2.3 was released.

https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12319527&version=12341608

**Comment by TaroKono** [comment]
@yu-iskw Hi,
Apache Beam SDK for Java versions 2.0.0 to 2.4.0 (inclusive) will be decommissioned in late 2019.
https://cloud.google.com/dataflow/docs/support/sdk-version-support-status

**Comment by yu-iskw** [comment]
@TaroKono Thank you for sharing it.
